const { uIOhook } = require('uiohook-napi');
const { mouse, screen, Point } = require('@nut-tree-fork/nut-js');
const { exec } = require('child_process');
const util = require('util');
const execPromise = util.promisify(exec);

class InputManager {
  constructor(webrtcManager, edgeMapping, localSocket) {
    this.webrtcManager = webrtcManager;
    this.edgeMapping = edgeMapping || {}; 
    this.localSocket = localSocket;
    
    this.activeRemoteTarget = null; 
    this.activeEdge = null; 
    this.controlledBy = null;
    
    this.screenBounds = { left: 0, right: 1920, top: 0, bottom: 1080 };
    
    this.justLocked = false;
    this.lockPoint = { x: 0, y: 0 };
    
    this.webrtcManager.on('message', async (sourceId, channel, message) => {
      if (channel === 'input-channel') {
        try {
          const data = JSON.parse(message);
          this.handleRemoteMessage(sourceId, data);
        } catch (err) {}
      }
    });
  }

  async getVirtualScreen() {
    try {
        const { stdout } = await execPromise('powershell.exe -command "Add-Type -AssemblyName System.Windows.Forms; [System.Windows.Forms.SystemInformation]::VirtualScreen"');
        const matchRight = stdout.match(/Right\s*:\s*(-?\d+)/);
        const matchLeft = stdout.match(/Left\s*:\s*(-?\d+)/);
        const matchTop = stdout.match(/Top\s*:\s*(-?\d+)/);
        const matchBottom = stdout.match(/Bottom\s*:\s*(-?\d+)/);
        
        if (matchRight && matchLeft) {
            return {
                left: parseInt(matchLeft[1], 10),
                right: parseInt(matchRight[1], 10),
                top: parseInt(matchTop[1], 10),
                bottom: parseInt(matchBottom[1], 10)
            };
        }
    } catch (e) {
        console.error("Failed to get virtual screen bounds:", e);
    }
    const w = await screen.width();
    const h = await screen.height();
    return { left: 0, right: w, top: 0, bottom: h };
  }

  async startEdgeDetection() {
    this.screenBounds = await this.getVirtualScreen();
    console.log("Detected screen bounds:", this.screenBounds);
    
    uIOhook.on('mousemove', async (e) => {
      // If we are currently being controlled by a remote PC, ignore all local physical mouse movements
      if (this.controlledBy) return;

      if (!this.activeRemoteTarget) {
        // Local control mode
        let crossedEdge = null;
        if (e.x >= this.screenBounds.right - 2 && this.edgeMapping.right) crossedEdge = 'right';
        if (e.x <= this.screenBounds.left + 1 && this.edgeMapping.left) crossedEdge = 'left';
        if (e.y <= this.screenBounds.top + 1 && this.edgeMapping.top) crossedEdge = 'top';
        if (e.y >= this.screenBounds.bottom - 2 && this.edgeMapping.bottom) crossedEdge = 'bottom';
        
        if (crossedEdge) {
          const targetId = this.edgeMapping[crossedEdge];
          if (this.webrtcManager.peers[targetId] && this.webrtcManager.peers[targetId].isConnected) {
            console.log(`Edge ${crossedEdge} crossed! Controlling peer ${targetId}`);
            this.activeRemoteTarget = targetId;
            this.activeEdge = crossedEdge;
            this.localSocket.emit('remote-status', { active: true, target: this.webrtcManager.peers[targetId].deviceName });
            
            // Tell remote we are taking control
            this.webrtcManager.sendInputMessage(targetId, JSON.stringify({ type: 'take-control', enterEdge: crossedEdge }));
            this.lockPoint = { x: e.x, y: e.y };
          }
        }
      } else {
        // Remote control mode (We are sending inputs to target)
        let lockX = this.activeEdge === 'right' ? this.screenBounds.right - 2 : (this.activeEdge === 'left' ? this.screenBounds.left + 1 : e.x);
        let lockY = this.activeEdge === 'bottom' ? this.screenBounds.bottom - 2 : (this.activeEdge === 'top' ? this.screenBounds.top + 1 : e.y);
        
        // Ignore the synthetic event generated by mouse.setPosition
        if (this.justLocked && Math.abs(e.x - this.lockPoint.x) <= 2 && Math.abs(e.y - this.lockPoint.y) <= 2) {
            this.justLocked = false;
            return;
        }

        const deltaX = e.x - lockX;
        const deltaY = e.y - lockY;

        if (deltaX !== 0 || deltaY !== 0) {
          const msg = JSON.stringify({ type: 'mousemove', dx: deltaX, dy: deltaY });
          this.webrtcManager.sendInputMessage(this.activeRemoteTarget, msg);
          
          this.justLocked = true;
          this.lockPoint = { x: lockX, y: lockY };
          await mouse.setPosition(new Point(lockX, lockY));
        }
      }
    });

    uIOhook.on('mousedown', (e) => {
      if (this.controlledBy) return;
      if (this.activeRemoteTarget) {
        this.webrtcManager.sendInputMessage(this.activeRemoteTarget, JSON.stringify({ type: 'mousedown', button: e.button }));
      }
    });

    uIOhook.on('mouseup', (e) => {
      if (this.controlledBy) return;
      if (this.activeRemoteTarget) {
        this.webrtcManager.sendInputMessage(this.activeRemoteTarget, JSON.stringify({ type: 'mouseup', button: e.button }));
      }
    });

    uIOhook.on('keydown', (e) => {
      if (this.controlledBy) return;
      if (this.activeRemoteTarget) {
        this.webrtcManager.sendInputMessage(this.activeRemoteTarget, JSON.stringify({ type: 'keydown', keycode: e.keycode }));
      }
    });

    uIOhook.on('keyup', (e) => {
      if (this.controlledBy) return;
      if (this.activeRemoteTarget) {
        this.webrtcManager.sendInputMessage(this.activeRemoteTarget, JSON.stringify({ type: 'keyup', keycode: e.keycode }));
      }
    });

    uIOhook.start();
  }

  async handleRemoteMessage(sourceId, data) {
    if (data.type === 'take-control') {
      console.log(`Being controlled by ${sourceId}`);
      this.controlledBy = sourceId;
      
      // Position our mouse at the entry edge
      if (!this.screenBounds) this.screenBounds = await this.getVirtualScreen();
      let startX = (this.screenBounds.left + this.screenBounds.right) / 2;
      let startY = (this.screenBounds.top + this.screenBounds.bottom) / 2;
      
      if (data.enterEdge === 'right') startX = this.screenBounds.left + 2;
      if (data.enterEdge === 'left') startX = this.screenBounds.right - 2;
      if (data.enterEdge === 'bottom') startY = this.screenBounds.top + 2;
      if (data.enterEdge === 'top') startY = this.screenBounds.bottom - 2;
      
      await mouse.setPosition(new Point(startX, startY));
    }
    else if (data.type === 'drop-control') {
      console.log(`Control dropped by ${sourceId}`);
      if (this.controlledBy === sourceId) this.controlledBy = null;
    }
    else if (data.type === 'edge-hit') {
       console.log(`Remote mouse hit edge: ${data.edge}`);
       // If the remote mouse hit the edge that connects back to us, we exit!
       if (this.activeEdge === 'right' && data.edge === 'left') this.exitRemoteMode();
       if (this.activeEdge === 'left' && data.edge === 'right') this.exitRemoteMode();
       if (this.activeEdge === 'top' && data.edge === 'bottom') this.exitRemoteMode();
       if (this.activeEdge === 'bottom' && data.edge === 'top') this.exitRemoteMode();
    }
    else if (this.controlledBy === sourceId) {
       this.injectInput(data);
    }
  }

  async injectInput(data) {
    if (data.type === 'mousemove') {
      const currentPos = await mouse.getPosition();
      
      let targetX = currentPos.x + data.dx;
      let targetY = currentPos.y + data.dy;
      
      let hitEdge = null;
      if (targetX <= this.screenBounds.left) { targetX = this.screenBounds.left; hitEdge = 'left'; }
      if (targetX >= this.screenBounds.right - 2) { targetX = this.screenBounds.right - 2; hitEdge = 'right'; }
      if (targetY <= this.screenBounds.top) { targetY = this.screenBounds.top; hitEdge = 'top'; }
      if (targetY >= this.screenBounds.bottom - 2) { targetY = this.screenBounds.bottom - 2; hitEdge = 'bottom'; }
      
      await mouse.setPosition(new Point(targetX, targetY));
      
      if (hitEdge) {
        // We hit the boundary of our virtual screen. Let the controller know.
        const msg = JSON.stringify({ type: 'edge-hit', edge: hitEdge });
        this.webrtcManager.sendInputMessage(this.controlledBy, msg);
      }
    }
    else if (data.type === 'mousedown') {
      await mouse.pressButton(data.button === 1 ? 0 : data.button === 2 ? 2 : 1);
    }
    else if (data.type === 'mouseup') {
      await mouse.releaseButton(data.button === 1 ? 0 : data.button === 2 ? 2 : 1);
    }
  }

  exitRemoteMode() {
    console.log('Exiting remote control mode.');
    if (this.activeRemoteTarget) {
       this.webrtcManager.sendInputMessage(this.activeRemoteTarget, JSON.stringify({ type: 'drop-control' }));
    }
    
    // Nudge the local mouse slightly away from the edge so it doesn't immediately re-trigger
    let escapeX = this.lockPoint.x;
    let escapeY = this.lockPoint.y;
    if (this.activeEdge === 'right') escapeX -= 100;
    if (this.activeEdge === 'left') escapeX += 100;
    if (this.activeEdge === 'top') escapeY += 100;
    if (this.activeEdge === 'bottom') escapeY -= 100;
    
    mouse.setPosition(new Point(escapeX, escapeY)).catch(()=>{});
    
    this.activeRemoteTarget = null;
    this.activeEdge = null;
    this.localSocket.emit('remote-status', { active: false, target: null });
  }

  setEdgeMapping(mapping) {
    this.edgeMapping = mapping || {};
  }

  stop() {
    uIOhook.stop();
  }
}

module.exports = InputManager;
