const { uIOhook } = require('uiohook-napi');
const { mouse, screen, Point } = require('@nut-tree-fork/nut-js');
const { exec } = require('child_process');
const util = require('util');
const execPromise = util.promisify(exec);

class InputManager {
  constructor(webrtcManager, edgeMapping, localSocket) {
    this.webrtcManager = webrtcManager;
    this.edgeMapping = edgeMapping || {}; 
    this.localSocket = localSocket;
    
    this.activeRemoteTarget = null; 
    this.activeEdge = null; 
    
    this.screenBounds = { left: 0, right: 1920, top: 0, bottom: 1080 };
    
    this.exitAccumulator = 0;
    this.justLocked = false;
    this.lockPoint = { x: 0, y: 0 };
    
    this.webrtcManager.on('message', async (sourceId, channel, message) => {
      if (channel === 'input-channel') {
        try {
          const data = JSON.parse(message);
          this.injectInput(data);
        } catch (err) {}
      }
    });
  }

  async getVirtualScreen() {
    try {
        const { stdout } = await execPromise('powershell.exe -command "Add-Type -AssemblyName System.Windows.Forms; [System.Windows.Forms.SystemInformation]::VirtualScreen"');
        const matchRight = stdout.match(/Right\s*:\s*(-?\d+)/);
        const matchLeft = stdout.match(/Left\s*:\s*(-?\d+)/);
        const matchTop = stdout.match(/Top\s*:\s*(-?\d+)/);
        const matchBottom = stdout.match(/Bottom\s*:\s*(-?\d+)/);
        
        if (matchRight && matchLeft) {
            return {
                left: parseInt(matchLeft[1], 10),
                right: parseInt(matchRight[1], 10),
                top: parseInt(matchTop[1], 10),
                bottom: parseInt(matchBottom[1], 10)
            };
        }
    } catch (e) {
        console.error("Failed to get virtual screen bounds:", e);
    }
    // Fallback to primary screen
    const w = await screen.width();
    const h = await screen.height();
    return { left: 0, right: w, top: 0, bottom: h };
  }

  async startEdgeDetection() {
    this.screenBounds = await this.getVirtualScreen();
    console.log("Detected screen bounds:", this.screenBounds);
    
    uIOhook.on('mousemove', async (e) => {
      if (!this.activeRemoteTarget) {
        // Local control mode
        let crossedEdge = null;
        if (e.x >= this.screenBounds.right - 2 && this.edgeMapping.right) crossedEdge = 'right';
        if (e.x <= this.screenBounds.left + 1 && this.edgeMapping.left) crossedEdge = 'left';
        if (e.y <= this.screenBounds.top + 1 && this.edgeMapping.top) crossedEdge = 'top';
        if (e.y >= this.screenBounds.bottom - 2 && this.edgeMapping.bottom) crossedEdge = 'bottom';
        
        if (crossedEdge) {
          const targetId = this.edgeMapping[crossedEdge];
          if (this.webrtcManager.peers[targetId] && this.webrtcManager.peers[targetId].isConnected) {
            console.log(`Edge ${crossedEdge} crossed! Controlling peer ${targetId}`);
            this.activeRemoteTarget = targetId;
            this.activeEdge = crossedEdge;
            this.exitAccumulator = 0;
            this.localSocket.emit('remote-status', { active: true, target: this.webrtcManager.peers[targetId].deviceName });
          }
        }
      } else {
        // Remote control mode
        let lockX = this.activeEdge === 'right' ? this.screenBounds.right - 2 : (this.activeEdge === 'left' ? this.screenBounds.left + 1 : e.x);
        let lockY = this.activeEdge === 'bottom' ? this.screenBounds.bottom - 2 : (this.activeEdge === 'top' ? this.screenBounds.top + 1 : e.y);
        
        // Ignore the synthetic event generated by mouse.setPosition
        if (this.justLocked && e.x === this.lockPoint.x && e.y === this.lockPoint.y) {
            this.justLocked = false;
            return;
        }

        const deltaX = e.x - lockX;
        const deltaY = e.y - lockY;

        // Track intent to break out (moving away from the remote screen edge)
        if (this.activeEdge === 'right') {
            if (deltaX < 0) this.exitAccumulator += deltaX; else this.exitAccumulator = 0;
        } else if (this.activeEdge === 'left') {
            if (deltaX > 0) this.exitAccumulator += deltaX; else this.exitAccumulator = 0;
        } else if (this.activeEdge === 'top') {
            if (deltaY > 0) this.exitAccumulator += deltaY; else this.exitAccumulator = 0;
        } else if (this.activeEdge === 'bottom') {
            if (deltaY < 0) this.exitAccumulator += deltaY; else this.exitAccumulator = 0;
        }

        // If they moved 100 pixels "backwards" consistently, break out of remote control
        if (Math.abs(this.exitAccumulator) > 100) {
            this.exitRemoteMode();
            return;
        }

        if (deltaX !== 0 || deltaY !== 0) {
          const msg = JSON.stringify({ type: 'mousemove', dx: deltaX, dy: deltaY });
          this.webrtcManager.sendInputMessage(this.activeRemoteTarget, msg);
          
          this.justLocked = true;
          this.lockPoint = { x: lockX, y: lockY };
          await mouse.setPosition(new Point(lockX, lockY));
        }
      }
    });

    uIOhook.on('mousedown', (e) => {
      if (this.activeRemoteTarget) {
        this.webrtcManager.sendInputMessage(this.activeRemoteTarget, JSON.stringify({ type: 'mousedown', button: e.button }));
      }
    });

    uIOhook.on('mouseup', (e) => {
      if (this.activeRemoteTarget) {
        this.webrtcManager.sendInputMessage(this.activeRemoteTarget, JSON.stringify({ type: 'mouseup', button: e.button }));
      }
    });

    uIOhook.on('keydown', (e) => {
      if (this.activeRemoteTarget) {
        this.webrtcManager.sendInputMessage(this.activeRemoteTarget, JSON.stringify({ type: 'keydown', keycode: e.keycode }));
      }
    });

    uIOhook.on('keyup', (e) => {
      if (this.activeRemoteTarget) {
        this.webrtcManager.sendInputMessage(this.activeRemoteTarget, JSON.stringify({ type: 'keyup', keycode: e.keycode }));
      }
    });

    uIOhook.start();
  }

  async injectInput(data) {
    if (data.type === 'mousemove') {
      const currentPos = await mouse.getPosition();
      
      // On the receiving end, we also need to respect virtual bounds so we don't go off-screen
      // But nut.js mouse.setPosition handles absolute coordinates.
      // If we don't bound it here, it might crash if it goes out of bounds.
      if (!this.screenBounds) this.screenBounds = await this.getVirtualScreen();
      
      const targetX = Math.max(this.screenBounds.left, Math.min(this.screenBounds.right, currentPos.x + data.dx));
      const targetY = Math.max(this.screenBounds.top, Math.min(this.screenBounds.bottom, currentPos.y + data.dy));
      await mouse.setPosition(new Point(targetX, targetY));
    }
    else if (data.type === 'mousedown') {
      await mouse.pressButton(data.button === 1 ? 0 : data.button === 2 ? 2 : 1);
    }
    else if (data.type === 'mouseup') {
      await mouse.releaseButton(data.button === 1 ? 0 : data.button === 2 ? 2 : 1);
    }
  }

  exitRemoteMode() {
    console.log('Exiting remote control mode.');
    this.activeRemoteTarget = null;
    this.activeEdge = null;
    this.exitAccumulator = 0;
    this.localSocket.emit('remote-status', { active: false, target: null });
  }

  setEdgeMapping(mapping) {
    this.edgeMapping = mapping || {};
  }

  stop() {
    uIOhook.stop();
  }
}

module.exports = InputManager;
